version: "3.8"

services:
  db:
    image: postgres:15
    container_name: subscription_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscription_engine
    ports:
      - "5432:5432"
    volumes:
      # This is the bind mount
      # It creates a 'postgres_data' folder in backend director
      - ./postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:alpine
  #   container_name: subscription_redis
  #   ports:
  #     - "6379:6379"
